spring.application.name=rag-app

server.port=8081

# OpenAI (Groq)
spring.ai.openai.api-key=api_key
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.model=llama-3.1-8b-instant

# Tree Retriever
spring.ai.tree-retriever.max-results=3
spring.ai.tree-retriever.traversal-deadline=3s
spring.ai.tree-retriever.llm-timeout=2s
spring.ai.tree-retriever.llm-retries=1
spring.ai.tree-retriever.branch-factor=4